### ISSUE TITLE
`name` is not part of JsonSchema spec

### ISSUE THREAD

**Issue by DeaconDesperado** [bcwaldon/warlock#16]
IIRC, the `name` field is not a required part of the JSONSchema spec.  The closest field I could find that would be analogous to this would be the `title` field, which is also optional (and human-readable.)  Warlock appears to use the `name` field to give the generated model it's class name.  Could we instead use a sanitized and titlecased version of the [id attribute](http://json-schema.org/latest/json-schema-core.html#anchor27), which is unique per schema?

**Comment by bcwaldon** [comment]
@DeaconDesperado I don't have the time to spend on warlock these days. I would be more than happy to review and merge a patch.

**Comment by bcwaldon** [comment]
I believe this was addressed by #18
