### ISSUE TITLE
Reference resolution issue

### ISSUE THREAD

**Issue by agbeltran** [bcwaldon/warlock#20]
When using warlock, I am getting an exception:
jsonschema.exceptions.RefResolutionError unknown url type
as I have different interdependent schemas in separate files.

From the code, it seems that it is not possible to set a resolver, correct? Do you know if there is another way to resolve this? 
Thanks.

**Comment by bcwaldon** [comment]
I honestly haven't used warlock in a few years now, so I don't believe I can be of much help. I'm happy to accept patches, but I personally won't be able to help you out here.

**Comment by agbeltran** [comment]
OK, thanks for letting me know

**Comment by bcwaldon** [comment]
@agbeltran can you check if this has been addressed in v1.3.0?
