### ISSUE TITLE
No version >3.5 available through conda-forge

### ISSUE THREAD

**Issue by behrm** [bcwaldon/warlock#30]
I tried to install warlock with conda into my Python 3.6 Installation and receive the following output:

`C:\Windows\system32>"c:\Program Files\ArcGIS\Pro\bin\Python\Scripts\conda" install -c conda-forge warlock
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - warlock -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.`

This is because warlock works only with Python 2.7?

**Comment by janw** [comment]
Hi @behrm!

Technically Warlock supports all Python versions 2.7 -- 3.7, but unfortunately the last version built through conda-forge is for 3.5. Just today I assumed maintainership for warlock, and will soon start updating the package and also work to get the version in conda-forge updated. Until then, I encourage you to use pip to install warlock instead.

**Comment by tschoonj** [comment]
@janw Could you give this another look? The conda-forge build is badly in need of some maintenance.

Are you a maintainer of the warlock conda-forge feedstock? I would gladly add myself as a maintainer and fix a thing or two...

**Comment by janw** [comment]
Unfortunately I’m not maintaining that currently but I’ll look into things more on the coming weekend. Gotta admit life got in the way over the past months.

**Comment by tschoonj** [comment]
I made myself a maintainer of the conda-forge feedstock and it's [up to date](https://github.com/conda-forge/warlock-feedstock/pull/6) now.

**Comment by janw** [comment]
Awesome, thank you!
