### ISSUE TITLE
Cannot install warlock==1.3.2 using Python 2.7

### ISSUE THREAD

**Issue by vijay-avi** [bcwaldon/warlock#41]
Attempting to install warlock==1.3.2 on a Python virtual environment (with Python==2.7.12 and pip==19.1.1, and setuptools==41.0.1) is resulting in the following error
`
$>virtualenv test-venv 
$>source test-venv/bin/activate 
$>python --version 
Python 2.7.12 
$>pip --version 
pip 19.1.1 from <pip path inside virtual environment> 
$> pip install warlock 
Collecting warlock==1.3.2 
  Using cached   https://files.pythonhosted.org/packages/7e/9b/648ceb3bc527e821c04d69f14facb0655268288ac7d8d6aa3a026c3316ea/warlock-1.3.2.tar.gz 
    ERROR: Complete output from command python setup.py egg_info: 
    ERROR: Traceback (most recent call last): 
      File "<string>", line 1, in <module> 
      File "/tmp/pip-install-V0WEIx/warlock/setup.py", line 37, in <module> 
        long_description=read("README.md"), 
      File "/tmp/pip-install-V0WEIx/warlock/setup.py", line 28, in read 
        os.path.join(os.path.dirname(__file__), fname), "r", encoding="utf-8" 
    TypeError: 'encoding' is an invalid keyword argument for this function 
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-V0WEIx/warlock/ 
`

I think the 'encoding' parameter is unavailable to [open()](https://docs.python.org/2/library/functions.html#open) in Python 2.7.12. To backport open() of Python 3 to Python 2.6/2.7, io.open can be used. 
Source:  Accepted solution from this [StackOverflow thread](https://stackoverflow.com/a/10975371).

**Comment by freddebacker** [comment]
Mine too...

```
Collecting warlock<2,>=1.2.0 (from python-glanceclient)
  Downloading https://files.pythonhosted.org/packages/7e/9b/648ceb3bc527e821c04d69f14facb0655268288ac7d8d6aa3a026c3316ea/warlock-1.3.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yl9AL5/warlock/setup.py", line 37, in <module>
        long_description=read("README.md"),
      File "/tmp/pip-install-yl9AL5/warlock/setup.py", line 28, in read
        os.path.join(os.path.dirname(__file__), fname), "r", encoding="utf-8"
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yl9AL5/warlock/
```

**Comment by willseeyou** [comment]
Me too.
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Cti6W0/warlock/setup.py", line 37, in <module>
        long_description=read("README.md"),
      File "/tmp/pip-build-Cti6W0/warlock/setup.py", line 28, in read
        os.path.join(os.path.dirname(__file__), fname), "r", encoding="utf-8"
    TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by art-vasilyev** [comment]
Looks like pull request #42 fixis this issue

**Comment by marios** [comment]
there is a pull request at https://github.com/bcwaldon/warlock/pull/42 from raukadah related to this

**Comment by 33man** [comment]
Me too :( 

```
Collecting warlock<2,>=1.2.0 (from python-glanceclient>=2.8.0->python-openstackclient->-r requirement.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/7e/9b/648ceb3bc527e821c04d69f14facb0655268288ac7d8d6aa3a026c3316ea/warlock-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rHiYZO/warlock/setup.py", line 37, in <module>
        long_description=read("README.md"),
      File "/tmp/pip-build-rHiYZO/warlock/setup.py", line 28, in read
        os.path.join(os.path.dirname(__file__), fname), "r", encoding="utf-8"
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rHiYZO/warlock/
```

**Comment by janw** [comment]
Sorry for all the trouble, still warming up to this. 🙈 Will publish 1.3.3 to PyPi in a bit.

**Comment by janw** [comment]
Again, sorry for the inconvenience caused. 1.3.3 is propagating on PyPi, and I've taken additional action to catch setup.py errors in CI in the future.

**Comment by 33man** [comment]
All good now 👍
